import { ArrowDown, ArrowUp, Medal } from 'lucide-react';
import { calculateRankings } from '@/services/tournamentLogic';
import type { Partie, RankingEntry, TurnierLiga } from '@/types';

export function Rangliste({ players, leagues, allMatches = [], currentRound = 1 }: { players: RankingEntry[]; leagues: TurnierLiga[]; allMatches?: Partie[]; currentRound?: number }) {
  const previousRankings = calculateRankings(players, allMatches.filter((match) => match.runde < currentRound));
  const previousRanks = new Map(previousRankings.map((player) => [String(player.id), player.rang]));
  const leagueNames = leagues.length ? leagues.sort((a, b) => a.reihenfolge - b.reihenfolge).map((league) => league.name) : [...new Set(players.map((player) => player.gruppe || 'Leicht'))];
   return <div><h2 className="mb-4 text-2xl font-bold">Turnier-Ranglisten</h2>{leagueNames.map((league) => { const entries = players.filter((player) => (player.gruppe || 'Leicht').toLowerCase() === league.toLowerCase()).sort((a, b) => a.rang - b.rang); return <section key={league} className="mb-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex justify-between border-b bg-slate-50 p-4"><h3 className="font-bold">Liga: {league}</h3><span className="text-xs text-slate-500">{entries.length} Spieler</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="px-4 py-2">Rang</th><th className="px-4 py-2">Spieler</th><th className="px-4 py-2 text-right">Punkte</th><th className="px-4 py-2 text-right">Buchholz</th><th className="px-4 py-2 text-right">SB</th></tr></thead><tbody className="divide-y divide-slate-100">{entries.map((player) => { const previousRank = previousRanks.get(String(player.id)); const movement = previousRank === undefined ? 0 : previousRank - player.rang; return <tr key={player.id} className="hover:bg-slate-50"><td className="px-4 py-2.5">{player.rang === 1 ? <Medal className="inline h-4 w-4 text-amber-500" /> : player.rang} {movement > 0 ? <ArrowUp className="inline h-4 w-4 font-bold text-emerald-600" /> : movement < 0 ? <ArrowDown className="inline h-4 w-4 font-bold text-rose-600" /> : <span className="text-slate-300">-</span>}</td><td className="px-4 py-2.5 font-medium">{player.name}</td><td className="px-4 py-2.5 text-right font-bold">{player.punkte}</td><td className="px-4 py-2.5 text-right text-slate-500">{player.buchholz}</td><td className="px-4 py-2.5 text-right text-slate-500">{player.sonnebornBerger}</td></tr>; })}</tbody></table></div></section>; })}</div>;
}